<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: bvickers
 * Date: Tue, 12 Aug 2014 11:22:14 +0200
 */

$conf['title'] = 'unMonastery wiki';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['notify'] = 'ben@vickers.tv';
$conf['registernotify'] = 'ben@vickers.tv';
$conf['plugin']['translation']['translations'] = 'it';
$conf['plugin']['translation']['dropdown'] = 1;
$conf['plugin']['translation']['display'] = 'name,UnitedKingdom';
$conf['plugin']['translation']['checkage'] = 1;
$conf['plugin']['translation']['copytrans'] = 1;
$conf['plugin']['markdownextra']['frontmatter'] = 1;

// end auto-generated content
